version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=parser_user
      - POSTGRES_PASSWORD=parser
      - POSTGRES_DB=population_db

  get_data:
    build: ./get_data
    volumes:
      - ./get_data:/app
    environment:
      - POSTGRES_USER=parser_user
      - POSTGRES_PASSWORD=parser
      - POSTGRES_DB=population_db
    depends_on:
      - db

  print_data:
    build: ./print_data
    volumes:
      - ./print_data:/app
    environment:
      - POSTGRES_USER=parser_user
      - POSTGRES_PASSWORD=parser
      - POSTGRES_DB=population_db
    depends_on:
      - db